### ISSUE TITLE
A few things to follow up before submission

### ISSUE THREAD

**Issue by zxzzhangg** [UBC-MDS/student_performance#11]
There are a few things we need to take care before submitting the milestone 1 tomorrow:
1. We need to add author and date to every script
2. We need to add more details for the Data Summary part of the final report.
3. All figures need a figure number and legend (e.g., Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)
4. We need to close the feedback issue with some comments.

**Comment by YenanZ** [comment]
I have closed the previous feedback issue with the TA, since we made all the improvements in release v2.0. 
As for the figure number and legends, pursuant to our previous discussion, I believe we are already good to go. We will address this if the TA gave any feedback, if not, remember we are not getting paid for this.

**Comment by YenanZ** [comment]
The have closed the previous issues.
Good suggestions.
